### PR TITLE
Switch SQLCipher to use mbedTLS instead of OpenSSL

### PR DESCRIPTION
**Pull request by borrrden**

### CODE REVIEW

**Comment by pasin** [comment]
@borrrden is this for 2.0 or also 1.x?

**Comment by borrrden** [comment]
This was designed for 2.0 but there is no reason it can't also be used for 1.x

**Comment by pasin** [comment]
@borrrden From https://www.zetetic.net/sqlcipher/design, it still doesn't say that it supports mbedTLS but from the PR there is `src/c/crypto_mbedtls.c`. Does the SQLCipher officially support mbedTLS?

**Comment by borrrden** [comment]
No. This is a custom provider that I wrote.

**Comment by NitzDKoder** [comment]
@pasin @borrrden please confirm CBL 1.4.1 uses mbedTLS or OpenSSL?

**Pull request merged**
